import ViewDashboard from "./dashboard/view/view_dashboard";
import ViewSum from "./summary/view/view_sum";
import ViewNationalp from "./nationalp/view/view_nationalp";
import ViewRegionals from "./regionals/view/view_regionals";
import ViewDemographicm from "./demographicm/view/view_demographicm";
import ViewAnalisak from "./analisak/view/view_analisak";
import ViewCoalitiont from "./coalitiont/view/view_coalitiont";
import ViewPemimpine from "./pemimpine/view/view_pemimpine";
import ViewAnalisas from "./analisas/view/view_analisas";
import ViewMlAi from "./ml-ai/view/view_ml-ai";
import ViewDemographicai from "./demographicai/view/view_demographicai";
import ViewPredictionm from "./predictionm/view/view_predictionm";
import ViewIssuem from "./issuem/view/view_issuem";
import ViewSpeciala from "./speciala/view/view_speciala";
import ViewStepa from "./stepa/view/view_stepa";
import ViewReportf from "./reportf/view/view_reportf";

export { ViewDashboard }
export { ViewSum }
export { ViewNationalp }
export { ViewRegionals }  
export { ViewDemographicm }
export { ViewAnalisak }
export { ViewCoalitiont }
export { ViewPemimpine }  
export { ViewAnalisas } 
export { ViewMlAi }
export { ViewDemographicai }
export { ViewPredictionm }
export { ViewIssuem }
export { ViewSpeciala }
export { ViewStepa }
export { ViewReportf }